openapi: 3.0.3
info:
  title: Employees API Spec
  description: Working with employee details
  version: v1
paths:
  /api/v1/employees:
    get:
      summary: Get list of employees
      responses:
        "200":
          description: Request to get list of employees
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  schemas:
    camelCaseComponent:
      type: object
    PascalCaseComponent1:
      type: object
      title: test-1
    PascalCaseComponent2:
      type: object
      description: |
        test-1